import { Inter } from "next/font/google";
import "./globals.css";
import "./framework.css";

import SideBar from "../components/SideBar/page";
import NavBar from "../components/NavBar/page";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Dashboard ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="main-sidebar" >
            <SideBar />
          </div>
          <div className="main-navbar" >
            <NavBar />
            {children}
          </div>
        </div>
      </body>
    </html >
  );
}
